name: Add Inventory Item
$kind: http-request
method: POST
url: http://localhost:8081/players/1/inventory
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |
    {
      "itemId": "coffee",
      "quantity": 3
    }
